name: Build .NET

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Get dependencies
      run: dotnet restore

    - run: dotnet build --no-restore

    - name: Build artifact
      uses: actions/upload-artifact@v2
      with:
        name: pptxtopdf
        path: release
